"""allow draft patient identification

Revision ID: 74a5cfe3dbce
Revises: 6cfdab072896
Create Date: 2026-08-23 11:25:30.301568

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '74a5cfe3dbce'
down_revision: str | None = '6cfdab072896'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='sex'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='sex'),
               nullable=False)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
